(global-set-key (kbd "C-c r") 'revert-buffer)
(global-set-key (kbd "C-c n") 'cleanup-buffer)
(global-set-key (kbd "M-z")   'undo)
(global-set-key (kbd "M-g")   'goto-line)
(global-set-key (kbd "M-a")   'mark-whole-buffer)
(global-set-key [f5] 'refresh-file)

;; (global-set-key (kbd "M-s") 'save-buffer)
;; (global-set-key [M-right] 'end-of-line)
;; (global-set-key [M-left] 'beginning-of-line)
